public enum MessageType {
    CONNECT,
    DISCONNECT,
    DATAITEM,
    CLEAR_DATAITEMS,
    ADD_NODE,
    REMOVE_NODE,
    DISCOVER,
    DATAITEMS_HASH_REQUEST,
    DATAITEMS_HASH,
    CHECK_INTEGRITY;
}
